import { ProviderCanonical, UtilityCategory } from '@/types';

// Mock provider database for common utilities
export const MOCK_PROVIDERS: ProviderCanonical[] = [
    // Electric
    {
        id: 'elec-001',
        normalized_name: 'Duke Energy',
        aliases: ['Duke Power', 'Duke Electric'],
        contact_phone: '1-800-777-9898',
        contact_urls: ['https://www.duke-energy.com/start-stop-move'],
        service_types: ['electric'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'elec-002',
        normalized_name: 'Florida Power & Light',
        aliases: ['FPL', 'Florida P&L'],
        contact_phone: '1-800-375-2434',
        contact_urls: ['https://www.fpl.com/moving.html'],
        service_types: ['electric'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'elec-003',
        normalized_name: 'Pacific Gas and Electric',
        aliases: ['PG&E', 'Pacific Gas & Electric'],
        contact_phone: '1-800-743-5000',
        contact_urls: ['https://www.pge.com/en/account/service-requests/start-stop-transfer-service.html'],
        service_types: ['electric', 'gas'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'elec-004',
        normalized_name: 'Southern California Edison',
        aliases: ['SCE', 'SoCal Edison'],
        contact_phone: '1-800-655-4555',
        contact_urls: ['https://www.sce.com/residential/start-stop-move-service'],
        service_types: ['electric'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'elec-005',
        normalized_name: 'Georgia Power',
        aliases: ['GA Power'],
        contact_phone: '1-888-660-5890',
        contact_urls: ['https://www.georgiapower.com/residential/start-stop-move/start-service.html'],
        service_types: ['electric'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'elec-006',
        normalized_name: 'ComEd',
        aliases: ['Commonwealth Edison'],
        contact_phone: '1-800-334-7661',
        contact_urls: ['https://www.comed.com/MyAccount/CustomerSupport/Pages/StartStopTransfer.aspx'],
        service_types: ['electric'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'elec-007',
        normalized_name: 'Dominion Energy',
        aliases: ['Dominion Virginia Power', 'Dominion'],
        contact_phone: '1-866-366-4357',
        contact_urls: ['https://www.dominionenergy.com/customer-service/start-stop-move-service'],
        service_types: ['electric', 'gas'],
        last_verified_at: '2024-01-15',
    },
    // Gas
    {
        id: 'gas-001',
        normalized_name: 'Piedmont Natural Gas',
        aliases: ['Piedmont Gas', 'PNG'],
        contact_phone: '1-800-752-7504',
        contact_urls: ['https://www.piedmontng.com/start-service'],
        service_types: ['gas'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'gas-002',
        normalized_name: 'SoCalGas',
        aliases: ['Southern California Gas', 'SoCal Gas'],
        contact_phone: '1-877-238-0092',
        contact_urls: ['https://www.socalgas.com/for-your-home/start-stop-service'],
        service_types: ['gas'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'gas-003',
        normalized_name: 'Nicor Gas',
        aliases: ['Nicor'],
        contact_phone: '1-888-642-6748',
        contact_urls: ['https://www.nicorgas.com/residential/start-stop-service.html'],
        service_types: ['gas'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'gas-004',
        normalized_name: 'Atlanta Gas Light',
        aliases: ['AGL', 'Atlanta Gas'],
        contact_phone: '1-877-427-4321',
        contact_urls: ['https://www.atlantagaslight.com/'],
        service_types: ['gas'],
        last_verified_at: '2024-01-15',
    },
    // Water
    {
        id: 'water-001',
        normalized_name: 'Charlotte Water',
        aliases: ['Charlotte-Mecklenburg Utility', 'CMU Water'],
        contact_phone: '311',
        contact_urls: ['https://charlottenc.gov/water/Pages/default.aspx'],
        service_types: ['water', 'sewer'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'water-002',
        normalized_name: 'American Water',
        aliases: ['American Water Works'],
        contact_phone: '1-800-272-1325',
        contact_urls: ['https://www.amwater.com/customer-service/'],
        service_types: ['water'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'water-003',
        normalized_name: 'LADWP',
        aliases: ['Los Angeles Department of Water and Power', 'LA Water'],
        contact_phone: '1-800-342-5397',
        contact_urls: ['https://www.ladwp.com/ladwp/cms/ladwp001644.jsp'],
        service_types: ['water', 'electric'],
        last_verified_at: '2024-01-15',
    },
    // Trash
    {
        id: 'trash-001',
        normalized_name: 'Waste Management',
        aliases: ['WM', 'Waste Mgmt'],
        contact_phone: '1-800-963-4776',
        contact_urls: ['https://www.wm.com/us/en/my-account'],
        service_types: ['trash'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'trash-002',
        normalized_name: 'Republic Services',
        aliases: ['Republic', 'Allied Waste'],
        contact_phone: '1-844-737-8254',
        contact_urls: ['https://www.republicservices.com/'],
        service_types: ['trash'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'trash-003',
        normalized_name: 'Waste Connections',
        aliases: [],
        contact_phone: '1-800-493-4493',
        contact_urls: ['https://www.wasteconnections.com/'],
        service_types: ['trash'],
        last_verified_at: '2024-01-15',
    },
    // Internet
    {
        id: 'inet-001',
        normalized_name: 'Spectrum',
        aliases: ['Charter Spectrum', 'Charter Communications', 'Time Warner Cable'],
        contact_phone: '1-833-267-6094',
        contact_urls: ['https://www.spectrum.com/'],
        service_types: ['internet'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'inet-002',
        normalized_name: 'Xfinity',
        aliases: ['Comcast', 'Comcast Xfinity'],
        contact_phone: '1-800-934-6489',
        contact_urls: ['https://www.xfinity.com/moving'],
        service_types: ['internet'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'inet-003',
        normalized_name: 'AT&T Internet',
        aliases: ['AT&T', 'AT&T Fiber'],
        contact_phone: '1-800-288-2020',
        contact_urls: ['https://www.att.com/internet/'],
        service_types: ['internet'],
        last_verified_at: '2024-01-15',
    },
    {
        id: 'inet-004',
        normalized_name: 'Google Fiber',
        aliases: ['GFiber'],
        contact_phone: '1-866-777-7550',
        contact_urls: ['https://fiber.google.com/'],
        service_types: ['internet'],
        last_verified_at: '2024-01-15',
    },
];

// State-based utility suggestions (mock AI logic)
export const STATE_PROVIDERS: Record<string, Record<UtilityCategory, string[]>> = {
    'NC': {
        electric: ['Duke Energy'],
        gas: ['Piedmont Natural Gas', 'Dominion Energy'],
        water: ['Charlotte Water', 'American Water'],
        sewer: ['Charlotte Water'],
        trash: ['Waste Management', 'Republic Services'],
        internet: ['Spectrum', 'AT&T Internet', 'Google Fiber'],
    },
    'FL': {
        electric: ['Florida Power & Light', 'Duke Energy'],
        gas: ['TECO Peoples Gas'],
        water: ['American Water'],
        sewer: [],
        trash: ['Waste Management', 'Waste Connections'],
        internet: ['Xfinity', 'Spectrum', 'AT&T Internet'],
    },
    'CA': {
        electric: ['Pacific Gas and Electric', 'Southern California Edison', 'LADWP'],
        gas: ['SoCalGas', 'Pacific Gas and Electric'],
        water: ['LADWP', 'American Water'],
        sewer: [],
        trash: ['Waste Management', 'Republic Services'],
        internet: ['Xfinity', 'Spectrum', 'AT&T Internet'],
    },
    'GA': {
        electric: ['Georgia Power'],
        gas: ['Atlanta Gas Light'],
        water: ['American Water'],
        sewer: [],
        trash: ['Waste Management', 'Republic Services'],
        internet: ['Xfinity', 'AT&T Internet', 'Google Fiber'],
    },
    'IL': {
        electric: ['ComEd'],
        gas: ['Nicor Gas'],
        water: ['American Water'],
        sewer: [],
        trash: ['Waste Management', 'Republic Services'],
        internet: ['Xfinity', 'AT&T Internet'],
    },
    'VA': {
        electric: ['Dominion Energy'],
        gas: ['Dominion Energy'],
        water: ['American Water'],
        sewer: [],
        trash: ['Waste Management', 'Republic Services'],
        internet: ['Xfinity', 'Spectrum'],
    },
};

// Default fallback providers for any state
export const DEFAULT_PROVIDERS: Record<UtilityCategory, string[]> = {
    electric: ['Duke Energy', 'Florida Power & Light'],
    gas: ['Piedmont Natural Gas'],
    water: ['American Water'],
    sewer: [],
    trash: ['Waste Management', 'Republic Services'],
    internet: ['Spectrum', 'Xfinity', 'AT&T Internet'],
};

// Utility category display info
export const UTILITY_CATEGORIES: { key: UtilityCategory; label: string; icon: string }[] = [
    { key: 'electric', label: 'Electric', icon: '⚡' },
    { key: 'gas', label: 'Natural Gas', icon: '🔥' },
    { key: 'water', label: 'Water', icon: '💧' },
    { key: 'sewer', label: 'Sewer', icon: '🚰' },
    { key: 'trash', label: 'Trash', icon: '🗑️' },
    { key: 'internet', label: 'Internet', icon: '📶' },
];
